import { CATEGORIES } from '../consts/consts';

export const dummyProducts = {
  ids: [
    'chicken eggs',
    'quail eggs',
    'milk',
    'curd',
    'sour cream',
    'beetroot',
    'cabbage',
    'carrot',
    'cucumber',
    'onion',
    'potato',
    'tomato',
    'apple',
    'pear',
    'peach',
    'plum',
    'blackberry',
    'strawberry',
    'cherry',
    'grape',
    'pork',
    'bacon',
    'beef',
    'bream',
    'carp',
    'catfish',
    'frozen fish',
    'frozen pork',
    'frozen beef',
    'honey in combs',
    'honey jars',
    'bread',
    'baget',
    'roll',
    'pita',
    'flat bread',
    'flour',
    'cereal',
    'pasta',
  ],
  entities: {
    'chicken eggs': {
      product_category: CATEGORIES.DAIRY_EGGS,
      items: {
        '01': {
          product_name: 'chicken eggs',
          seller_id: '01',
          product_weight: '10 pcs',
          product_price: '2.5',
          product_image: 'chicken_eggs.jpg',
        },
        '02': {
          product_name: 'chicken eggs',
          seller_id: '02',
          product_weight: '10 pcs',
          product_price: '2.4',
          product_image: 'chicken_eggs2.jpg',
        },
        '03': {
          product_name: 'chicken eggs',
          seller_id: '03',
          product_weight: '10 pcs',
          product_price: '2',
          product_image: 'chicken_eggs3.jpg',
        },
        '04': {
          product_name: 'chicken eggs',
          seller_id: '04',
          product_weight: '10 pcs',
          product_price: '2.2',
          product_image: 'chicken_eggs4.jpg',
        },
        '05': {
          product_name: 'chicken eggs',
          seller_id: '05',
          product_weight: '10 pcs',
          product_price: '2.5',
          product_image: 'chicken_eggs5.jpg',
        },
      },
    },
    'quail eggs': {
      product_category: CATEGORIES.DAIRY_EGGS,
      items: {
        '01': {
          product_name: 'quail eggs',
          seller_id: '01',
          product_weight: '10 pcs',
          product_price: '2.5',
          product_image: 'quail_eggs.jpg',
        },
        '02': {
          product_name: 'quail eggs',
          seller_id: '02',
          product_weight: '10 pcs',
          product_price: '2.4',
          product_image: 'quail_eggs2.jpg',
        },
        '03': {
          product_name: 'quail eggs',
          seller_id: '03',
          product_weight: '10 pcs',
          product_price: '2',
          product_image: 'quail_eggs3.jpg',
        },
        '04': {
          product_name: 'quail eggs',
          seller_id: '04',
          product_weight: '10 pcs',
          product_price: '2.2',
          product_image: 'quail_eggs4.jpg',
        },
        '05': {
          product_name: 'quail eggs',
          seller_id: '05',
          product_weight: '10 pcs',
          product_price: '2.5',
          product_image: 'quail_eggs5.jpg',
        },
      },
    },
    milk: {
      product_category: CATEGORIES.DAIRY_EGGS,
      items: {
        '01': {
          product_name: 'milk',
          seller_id: '01',
          product_weight: '1 liter',
          product_price: '2.5',
          product_image: 'milk1.jpg',
        },
        '02': {
          product_name: 'milk',
          seller_id: '02',
          product_weight: '1 liter',
          product_price: '2.4',
          product_image: 'milk2.jpg',
        },
        '03': {
          product_name: 'milk',
          seller_id: '03',
          product_weight: '1 liter',
          product_price: '2.8',
          product_image: 'milk3.jpg',
        },
        '04': {
          product_name: 'milk',
          seller_id: '04',
          product_weight: '1 liter',
          product_price: '2.2',
          product_image: 'milk4.jpg',
        },
      },
    },
    curd: {
      product_category: CATEGORIES.DAIRY_EGGS,
      items: {
        '01': {
          product_name: 'curd',
          seller_id: '01',
          product_weight: '1 kg',
          product_price: '4.5',
          product_image: 'curd1.jpg',
        },
        '02': {
          product_name: 'curd',
          seller_id: '02',
          product_weight: '1 kg',
          product_price: '4.4',
          product_image: 'curd2.jpg',
        },
        '03': {
          product_name: 'curd',
          seller_id: '03',
          product_weight: '1 kg',
          product_price: '4.8',
          product_image: 'curd3.jpg',
        },
        '04': {
          product_name: 'curd',
          seller_id: '04',
          product_weight: '1 kg',
          product_price: '4.2',
          product_image: 'curd4.jpg',
        },
      },
    },

    'sour cream': {
      product_category: CATEGORIES.DAIRY_EGGS,
      items: {
        '01': {
          product_name: 'sour cream',
          seller_id: '01',
          product_weight: '1 kg',
          product_price: '4.5',
          product_image: 'sour_cream1.jpg',
        },
        '02': {
          product_name: 'sour cream',
          seller_id: '02',
          product_weight: '1 kg',
          product_price: '4.4',
          product_image: 'sour_cream2.jpg',
        },
        '03': {
          product_name: 'sour cream',
          seller_id: '03',
          product_weight: '1 kg',
          product_price: '4.8',
          product_image: 'sour_cream3.jpg',
        },
        '04': {
          product_name: 'sour cream',
          seller_id: '04',
          product_weight: '1 kg',
          product_price: '4.2',
          product_image: 'sour_cream4.jpg',
        },
      },
    },
    beetroot: {
      product_category: CATEGORIES.VEGETABLES,
      items: {
        '01': {
          product_name: 'beetroot',
          seller_id: '06',
          product_weight: '1 kg',
          product_price: '0.5',
          product_image: 'beetroot1.jpg',
        },
        '02': {
          product_name: 'beetroot',
          seller_id: '07',
          product_weight: '1 kg',
          product_price: '0.4',
          product_image: 'beetroot2.jpg',
        },
        '03': {
          product_name: 'beetroot',
          seller_id: '08',
          product_weight: '1 kg',
          product_price: '0.8',
          product_image: 'beetroot3.jpg',
        },
        '04': {
          product_name: 'beetroot',
          seller_id: '09',
          product_weight: '1 kg',
          product_price: '0.4',
          product_image: 'beetroot4.jpg',
        },
      },
    },
    cabbage: {
      product_category: CATEGORIES.VEGETABLES,
      items: {
        '01': {
          product_name: 'cabbage',
          seller_id: '06',
          product_weight: '1 kg',
          product_price: '0.5',
          product_image: 'cabbage1.jpg',
        },
        '02': {
          product_name: 'cabbage',
          seller_id: '07',
          product_weight: '1 kg',
          product_price: '0.4',
          product_image: 'cabbage2.jpg',
        },
        '03': {
          product_name: 'cabbage',
          seller_id: '08',
          product_weight: '1 kg',
          product_price: '0.8',
          product_image: 'cabbage3.jpg',
        },
        '04': {
          product_name: 'cabbage',
          seller_id: '09',
          product_weight: '1 kg',
          product_price: '0.4',
          product_image: 'cabbage4.jpg',
        },
      },
    },
    carrot: {
      product_category: CATEGORIES.VEGETABLES,
      items: {
        '01': {
          product_name: 'carrot',
          seller_id: '06',
          product_weight: '1 kg',
          product_price: '0.5',
          product_image: 'carrot1.jpg',
        },
        '02': {
          product_name: 'carrot',
          seller_id: '07',
          product_weight: '1 kg',
          product_price: '0.4',
          product_image: 'carrot2.jpg',
        },
        '03': {
          product_name: 'carrot',
          seller_id: '08',
          product_weight: '1 kg',
          product_price: '0.8',
          product_image: 'carrot3.jpg',
        },
        '04': {
          product_name: 'carrot',
          seller_id: '09',
          product_weight: '1 kg',
          product_price: '0.4',
          product_image: 'carrot4.jpg',
        },
      },
    },
    cucumber: {
      product_category: CATEGORIES.VEGETABLES,
      items: {
        '01': {
          product_name: 'cucumber',
          seller_id: '06',
          product_weight: '1 kg',
          product_price: '0.5',
          product_image: 'cucumber1.jpg',
        },
        '02': {
          product_name: 'cucumber',
          seller_id: '07',
          product_weight: '1 kg',
          product_price: '0.4',
          product_image: 'cucumber2.jpg',
        },
        '03': {
          product_name: 'cucumber',
          seller_id: '08',
          product_weight: '1 kg',
          product_price: '0.8',
          product_image: 'cucumber3.jpg',
        },
        '04': {
          product_name: 'cucumber',
          seller_id: '04',
          product_weight: '1 kg',
          product_price: '0.4',
          product_image: 'cucumber4.jpg',
        },
      },
    },
    onion: {
      product_category: CATEGORIES.VEGETABLES,
      items: {
        '01': {
          product_name: 'onion',
          seller_id: '06',
          product_weight: '1 kg',
          product_price: '0.5',
          product_image: 'onion1.jpg',
        },
        '02': {
          product_name: 'onion',
          seller_id: '07',
          product_weight: '1 kg',
          product_price: '0.4',
          product_image: 'onion2.jpg',
        },
        '03': {
          product_name: 'onion',
          seller_id: '08',
          product_weight: '1 kg',
          product_price: '0.8',
          product_image: 'onion3.jpg',
        },
        '04': {
          product_name: 'onion',
          seller_id: '09',
          product_weight: '1 kg',
          product_price: '0.4',
          product_image: 'onion4.jpg',
        },
      },
    },
    potato: {
      product_category: CATEGORIES.VEGETABLES,
      items: {
        '01': {
          product_name: 'potato',
          seller_id: '06',
          product_weight: '1 kg',
          product_price: '0.5',
          product_image: 'potato1.jpg',
        },
        '02': {
          product_name: 'potato',
          seller_id: '07',
          product_weight: '1 kg',
          product_price: '0.4',
          product_image: 'potato2.jpg',
        },
        '03': {
          product_name: 'potato',
          seller_id: '08',
          product_weight: '1 kg',
          product_price: '0.8',
          product_image: 'potato3.jpg',
        },
        '04': {
          product_name: 'potato',
          seller_id: '09',
          product_weight: '1 kg',
          product_price: '0.4',
          product_image: 'potato4.jpg',
        },
      },
    },
    tomato: {
      product_category: CATEGORIES.VEGETABLES,
      items: {
        '01': {
          product_name: 'tomato',
          seller_id: '04',
          product_weight: '1 kg',
          product_price: '0.5',
          product_image: 'tomato1.jpg',
        },
        '02': {
          product_name: 'tomato',
          seller_id: '07',
          product_weight: '1 kg',
          product_price: '0.4',
          product_image: 'tomato2.jpg',
        },
        '03': {
          product_name: 'tomato',
          seller_id: '08',
          product_weight: '1 kg',
          product_price: '0.8',
          product_image: 'tomato3.jpg',
        },
        '04': {
          product_name: 'tomato',
          seller_id: '09',
          product_weight: '1 kg',
          product_price: '0.4',
          product_image: 'tomato4.jpg',
        },
      },
    },
    apple: {
      product_category: CATEGORIES.FRUITS,
      items: {
        '01': {
          product_name: 'apple',
          seller_id: '06',
          product_weight: '1 kg',
          product_price: '1.5',
          product_image: 'apple1.jpg',
        },
        '02': {
          product_name: 'apple',
          seller_id: '07',
          product_weight: '1 kg',
          product_price: '1.4',
          product_image: 'apple2.jpg',
        },
        '03': {
          product_name: 'apple',
          seller_id: '08',
          product_weight: '1 kg',
          product_price: '1.8',
          product_image: 'apple3.jpg',
        },
        '04': {
          product_name: 'apple',
          seller_id: '09',
          product_weight: '1 kg',
          product_price: '1.4',
          product_image: 'apple4.jpg',
        },
      },
    },
    pear: {
      product_category: CATEGORIES.FRUITS,
      items: {
        '01': {
          product_name: 'pear',
          seller_id: '06',
          product_weight: '1 kg',
          product_price: '1.5',
          product_image: 'pear1.jpg',
        },
        '02': {
          product_name: 'pear',
          seller_id: '07',
          product_weight: '1 kg',
          product_price: '1.4',
          product_image: 'pear2.jpg',
        },
        '03': {
          product_name: 'pear',
          seller_id: '08',
          product_weight: '1 kg',
          product_price: '1.8',
          product_image: 'pear3.jpg',
        },
        '04': {
          product_name: 'pear',
          seller_id: '09',
          product_weight: '1 kg',
          product_price: '1.4',
          product_image: 'pear4.jpg',
        },
      },
    },
    peach: {
      product_category: CATEGORIES.FRUITS,
      items: {
        '01': {
          product_name: 'peach',
          seller_id: '06',
          product_weight: '1 kg',
          product_price: '1.5',
          product_image: 'peach1.jpg',
        },
        '02': {
          product_name: 'peach',
          seller_id: '07',
          product_weight: '1 kg',
          product_price: '1.4',
          product_image: 'peach2.jpg',
        },
        '03': {
          product_name: 'peach',
          seller_id: '02',
          product_weight: '1 kg',
          product_price: '1.8',
          product_image: 'peach3.jpg',
        },
        '04': {
          product_name: 'peach',
          seller_id: '09',
          product_weight: '1 kg',
          product_price: '1.4',
          product_image: 'peach4.jpg',
        },
      },
    },
    plum: {
      product_category: CATEGORIES.FRUITS,
      items: {
        '01': {
          product_name: 'plum',
          seller_id: '06',
          product_weight: '1 kg',
          product_price: '1.5',
          product_image: 'plum1.jpg',
        },
        '02': {
          product_name: 'plum',
          seller_id: '08',
          product_weight: '1 kg',
          product_price: '1.4',
          product_image: 'plum2.jpg',
        },
        '03': {
          product_name: 'plum',
          seller_id: '02',
          product_weight: '1 kg',
          product_price: '1.8',
          product_image: 'plum3.jpg',
        },
        '04': {
          product_name: 'plum',
          seller_id: '09',
          product_weight: '1 kg',
          product_price: '1.4',
          product_image: 'plum4.jpg',
        },
      },
    },
    strawberry: {
      product_category: CATEGORIES.BERRIES,
      items: {
        '01': {
          product_name: 'strawberry',
          seller_id: '06',
          product_weight: '1 kg',
          product_price: '1.5',
          product_image: 'strawberry1.jpg',
        },
        '02': {
          product_name: 'strawberry',
          seller_id: '08',
          product_weight: '1 kg',
          product_price: '1.4',
          product_image: 'strawberry2.jpg',
        },
        '03': {
          product_name: 'strawberry',
          seller_id: '02',
          product_weight: '1 kg',
          product_price: '1.8',
          product_image: 'strawberry3.jpg',
        },
        '04': {
          product_name: 'strawberry',
          seller_id: '09',
          product_weight: '1 kg',
          product_price: '1.4',
          product_image: 'strawberry4.jpg',
        },
      },
    },
    blackberry: {
      product_category: CATEGORIES.BERRIES,
      items: {
        '01': {
          product_name: 'blackberry',
          seller_id: '06',
          product_weight: '1 kg',
          product_price: '1.5',
          product_image: 'blackberry1.jpg',
        },
        '02': {
          product_name: 'blackberry',
          seller_id: '08',
          product_weight: '1 kg',
          product_price: '1.4',
          product_image: 'blackberry2.jpg',
        },
        '03': {
          product_name: 'blackberry',
          seller_id: '02',
          product_weight: '1 kg',
          product_price: '1.8',
          product_image: 'blackberry3.jpg',
        },
        '04': {
          product_name: 'blackberry',
          seller_id: '09',
          product_weight: '1 kg',
          product_price: '1.4',
          product_image: 'blackberry4.jpg',
        },
      },
    },
    cherry: {
      product_category: CATEGORIES.BERRIES,
      items: {
        '01': {
          product_name: 'cherry',
          seller_id: '06',
          product_weight: '1 kg',
          product_price: '1.5',
          product_image: 'cherry1.jpg',
        },
        '02': {
          product_name: 'cherry',
          seller_id: '08',
          product_weight: '1 kg',
          product_price: '1.4',
          product_image: 'cherry2.jpg',
        },
        '03': {
          product_name: 'cherry',
          seller_id: '02',
          product_weight: '1 kg',
          product_price: '1.8',
          product_image: 'cherry3.jpg',
        },
      },
    },
    grape: {
      product_category: CATEGORIES.BERRIES,
      items: {
        '01': {
          product_name: 'grape',
          seller_id: '08',
          product_weight: '1 kg',
          product_price: '1.5',
          product_image: 'grape1.jpg',
        },
        '02': {
          product_name: 'grape',
          seller_id: '09',
          product_weight: '1 kg',
          product_price: '1.4',
          product_image: 'grape2.jpg',
        },
        '03': {
          product_name: 'grape',
          seller_id: '02',
          product_weight: '1 kg',
          product_price: '1.8',
          product_image: 'grape3.jpg',
        },
      },
    },
    pork: {
      product_category: CATEGORIES.MEAT,
      items: {
        '01': {
          product_name: 'pork',
          seller_id: '01',
          product_weight: '1 kg',
          product_price: '4.5',
          product_image: 'pork1.jpg',
        },
        '02': {
          product_name: 'pork',
          seller_id: '03',
          product_weight: '1 kg',
          product_price: '4.4',
          product_image: 'pork2.jpg',
        },
        '03': {
          product_name: 'pork',
          seller_id: '04',
          product_weight: '1 kg',
          product_price: '4.8',
          product_image: 'pork3.jpg',
        },
      },
    },

    bacon: {
      product_category: CATEGORIES.MEAT,
      items: {
        '01': {
          product_name: 'bacon',
          seller_id: '01',
          product_weight: '1 kg',
          product_price: '4.5',
          product_image: 'bacon1.jpg',
        },
        '02': {
          product_name: 'bacon',
          seller_id: '03',
          product_weight: '1 kg',
          product_price: '4.4',
          product_image: 'bacon2.jpg',
        },
        '03': {
          product_name: 'bacon',
          seller_id: '04',
          product_weight: '1 kg',
          product_price: '4.8',
          product_image: 'bacon3.jpg',
        },
      },
    },
    beef: {
      product_category: CATEGORIES.MEAT,
      items: {
        '01': {
          product_name: 'beef',
          seller_id: '01',
          product_weight: '1 kg',
          product_price: '5.5',
          product_image: 'beef1.jpg',
        },
        '02': {
          product_name: 'beef',
          seller_id: '03',
          product_weight: '1 kg',
          product_price: '5.4',
          product_image: 'beef2.jpg',
        },
      },
    },
    bream: {
      product_category: CATEGORIES.FISH,
      items: {
        '01': {
          product_name: 'bream',
          seller_id: '10',
          product_weight: '1 kg',
          product_price: '5.5',
          product_image: 'bream.jpg',
        },
      },
    },
    carp: {
      product_category: CATEGORIES.FISH,
      items: {
        '01': {
          product_name: 'carp',
          seller_id: '10',
          product_weight: '1 kg',
          product_price: '5.5',
          product_image: 'carp.jpg',
        },
      },
    },
    catfish: {
      product_category: CATEGORIES.FISH,
      items: {
        '01': {
          product_name: 'catfish',
          seller_id: '10',
          product_weight: '1 kg',
          product_price: '5.5',
          product_image: 'catfish.jpg',
        },
      },
    },
    'frozen fish': {
      product_category: CATEGORIES.FROZEN,
      items: {
        '01': {
          product_name: 'frozen fish',
          seller_id: '10',
          product_weight: '1 kg',
          product_price: '2.5',
          product_image: 'frozen_fish.jpg',
        },
      },
    },
    'frozen pork': {
      product_category: CATEGORIES.FROZEN,
      items: {
        '01': {
          product_name: 'frozen pork',
          seller_id: '01',
          product_weight: '1 kg',
          product_price: '4.5',
          product_image: 'frozen_pork1.jpg',
        },
        '02': {
          product_name: 'frozen pork',
          seller_id: '03',
          product_weight: '1 kg',
          product_price: '4.4',
          product_image: 'frozen_pork2.jpg',
        },
      },
    },
    'frozen beef': {
      product_category: CATEGORIES.FROZEN,
      items: {
        '01': {
          product_name: 'frozen beef',
          seller_id: '01',
          product_weight: '1 kg',
          product_price: '4.5',
          product_image: 'frozen_beef1.jpg',
        },
        '02': {
          product_name: 'frozen beef',
          seller_id: '03',
          product_weight: '1 kg',
          product_price: '4.4',
          product_image: 'frozen_beef2.jpg',
        },
      },
    },
    'honey in combs': {
      product_category: CATEGORIES.HONEY,
      items: {
        '01': {
          product_name: 'honey in combs',
          seller_id: '11',
          product_weight: '1 kg',
          product_price: '10.1',
          product_image: 'honey_in_combs.jpg',
        },
      },
    },
    'honey jars': {
      product_category: CATEGORIES.HONEY,
      items: {
        '01': {
          product_name: 'honey jars',
          seller_id: '11',
          product_weight: '1 jar',
          product_price: '8.1',
          product_image: 'honey_jars.jpg',
        },
      },
    },
    bread: {
      product_category: CATEGORIES.BAKERY,
      items: {
        '01': {
          product_name: 'bread',
          seller_id: '12',
          product_weight: '1 pcs',
          product_price: '0.7',
          product_image: 'bread1.jpg',
        },
        '02': {
          product_name: 'bread',
          seller_id: '13',
          product_weight: '1 pcs',
          product_price: '0.6',
          product_image: 'bread2.jpg',
        },
        '03': {
          product_name: 'bread',
          seller_id: '14',
          product_weight: '1 pcs',
          product_price: '0.8',
          product_image: 'bread3.jpg',
        },
      },
    },
    baget: {
      product_category: CATEGORIES.BAKERY,
      items: {
        '01': {
          product_name: 'baget',
          seller_id: '12',
          product_weight: '1 pcs',
          product_price: '0.5',
          product_image: 'baget1.jpg',
        },
        '02': {
          product_name: 'baget',
          seller_id: '13',
          product_weight: '1 pcs',
          product_price: '0.4',
          product_image: 'baget2.jpg',
        },
        '03': {
          product_name: 'baget',
          seller_id: '14',
          product_weight: '1 pcs',
          product_price: '0.4',
          product_image: 'baget3.jpg',
        },
      },
    },
    roll: {
      product_category: CATEGORIES.BAKERY,
      items: {
        '01': {
          product_name: 'roll',
          seller_id: '12',
          product_weight: '6 pcs',
          product_price: '0.5',
          product_image: 'roll1.jpg',
        },
        '02': {
          product_name: 'roll',
          seller_id: '13',
          product_weight: '6 pcs',
          product_price: '0.6',
          product_image: 'roll2.jpg',
        },
        '03': {
          product_name: 'roll',
          seller_id: '14',
          product_weight: '6 pcs',
          product_price: '0.8',
          product_image: 'roll3.jpg',
        },
      },
    },
    pita: {
      product_category: CATEGORIES.BAKERY,
      items: {
        '01': {
          product_name: 'pita',
          seller_id: '14',
          product_weight: '1 pack',
          product_price: '1.1',
          product_image: 'pita.jpg',
        },
      },
    },
    'flat bread': {
      product_category: CATEGORIES.BAKERY,
      items: {
        '01': {
          product_name: 'flat bread',
          seller_id: '14',
          product_weight: '1 pack',
          product_price: '1.1',
          product_image: 'flat_bread.jpg',
        },
      },
    },
    flour: {
      product_category: CATEGORIES.GROCERY,
      items: {
        '01': {
          product_name: 'flour',
          seller_id: '12',
          product_weight: '1 kg',
          product_price: '0.5',
          product_image: 'flour1.jpg',
        },
        '02': {
          product_name: 'flour',
          seller_id: '13',
          product_weight: '1 kg',
          product_price: '0.6',
          product_image: 'flour2.jpg',
        },
        '03': {
          product_name: 'flour',
          seller_id: '14',
          product_weight: '1 kg',
          product_price: '0.8',
          product_image: 'flour3.jpg',
        },
      },
    },
    cereal: {
      product_category: CATEGORIES.GROCERY,
      items: {
        '01': {
          product_name: 'cereal',
          seller_id: '12',
          product_weight: '1 pack',
          product_price: '2.5',
          product_image: 'cereal1.jpg',
        },
        '02': {
          product_name: 'cereal',
          seller_id: '13',
          product_weight: '1 pack',
          product_price: '2.6',
          product_image: 'cereal2.jpg',
        },
        '03': {
          product_name: 'cereal',
          seller_id: '14',
          product_weight: '1 pack',
          product_price: '2.4',
          product_image: 'cereal3.jpg',
        },
      },
    },
    pasta: {
      product_category: CATEGORIES.GROCERY,
      items: {
        '01': {
          product_name: 'pasta',
          seller_id: '12',
          product_weight: '1 kg',
          product_price: '1.5',
          product_image: 'pasta1.jpg',
        },
        '02': {
          product_name: 'pasta',
          seller_id: '13',
          product_weight: '1 kg',
          product_price: '1.6',
          product_image: 'pasta2.jpg',
        },
      },
    },
  },
};
