import { CATEGORIES } from '../consts/consts';

export const dummyProducts = {
  ids: ['chicken eggs', 'quail eggs'],
  entities: {
    'chicken eggs': {
      product_category: CATEGORIES.DAIRY_EGGS,
      items: {
        '01': {
          product_name: 'chicken eggs',
          seller_id: '01',
          product_weight: '10 pcs',
          product_price: '2.5',
          product_image: 'chicken_eggs.jpg',
        },
        '02': {
          product_name: 'chicken eggs',
          seller_id: '02',
          product_weight: '10 pcs',
          product_price: '2.4',
          product_image: 'chicken_eggs2.jpg',
        },
        '03': {
          product_name: 'chicken eggs',
          seller_id: '03',
          product_weight: '10 pcs',
          product_price: '2',
          product_image: 'chicken_eggs3.jpg',
        },
        '04': {
          product_name: 'chicken eggs',
          seller_id: '04',
          product_weight: '10 pcs',
          product_price: '2.2',
          product_image: 'chicken_eggs4.jpg',
        },
        '05': {
          product_name: 'chicken eggs',
          seller_id: '05',
          product_weight: '10 pcs',
          product_price: '2.5',
          product_image: 'chicken_eggs5.jpg',
        },
      },
    },
    'quail eggs': {
      product_category: CATEGORIES.DAIRY_EGGS,
      items: {
        '01': {
          product_name: 'quail eggs',
          seller_id: '01',
          product_weight: '10 pcs',
          product_price: '2.5',
          product_image: 'quail_eggs.jpg',
        },
        '02': {
          product_name: 'quail eggs',
          seller_id: '02',
          product_weight: '10 pcs',
          product_price: '2.4',
          product_image: 'quail_eggs2.jpg',
        },
        '03': {
          product_name: 'quail eggs',
          seller_id: '03',
          product_weight: '10 pcs',
          product_price: '2',
          product_image: 'quail_eggs3.jpg',
        },
        '04': {
          product_name: 'quail eggs',
          seller_id: '04',
          product_weight: '10 pcs',
          product_price: '2.2',
          product_image: 'quail_eggs4.jpg',
        },
        '05': {
          product_name: 'quail eggs',
          seller_id: '05',
          product_weight: '10 pcs',
          product_price: '2.5',
          product_image: 'quail_eggs5.jpg',
        },
      },
    },
  },
};

// '03': {
//   seller_id: ['01', '02', '03', '04', '05', '06'],
//   product_category: CATEGORIES.DAIRY_EGGS,
//   product_name: 'Cow milk',
//   product_weight: '1 liter',
//   product_price: '2',
//   product_image: 'cow_milk.jpg',
// },
// '04': {
//   seller_id: ['04', '05'],
//   product_category: CATEGORIES.DAIRY_EGGS,
//   product_name: 'Goat milk',
//   product_weight: '1 liter',
//   product_price: '2',
//   product_image: 'goat_milk.jpg',
// },
// '05': {
//   seller_id: ['04', '05'],
//   product_category: CATEGORIES.DAIRY_EGGS,
//   product_name: 'Fermented baked milk',
//   product_weight: '1 liter',
//   product_price: '2',
//   product_image: 'fermented_baked_milk.jpg',
// },
// '06': {
//   seller_id: ['01', '02', '03', '04', '05', '06'],
//   product_category: CATEGORIES.DAIRY_EGGS,
//   product_name: 'Curd',
//   product_weight: '1 kg',
//   product_price: '2',
//   product_image: 'curd.jpg',
// },
// '07': {
//   seller_id: ['04', '05'],
//   product_category: CATEGORIES.DAIRY_EGGS,
//   product_name: 'Circassian cheese',
//   product_weight: '1 kg',
//   product_price: '2',
//   product_image: 'circassian_cheese.jpg',
// },
// '08': {
//   seller_id: ['01', '02', '03', '04', '05', '06'],
//   product_category: CATEGORIES.DAIRY_EGGS,
//   product_name: 'Brynza cheese',
//   product_weight: '1 liter',
//   product_price: '2',
//   product_image: 'brynza_cheese.jpg',
// },
